# **Análisis de Sentimientos en Música**

In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

# Datos de ejemplo
lyrics = ["I'm so happy today", "Feeling sad and blue", "This is the best day ever", "I'm feeling down"]
labels = [1, 0, 1, 0]


tokenizer = Tokenizer(num_words=10000)
tokenizer.fit_on_texts(lyrics)
sequences = tokenizer.texts_to_sequences(lyrics)
padded_sequences = pad_sequences(sequences, padding='post')


model = Sequential([
    Embedding(input_dim=10000, output_dim=16, input_length=padded_sequences.shape[1]),
    LSTM(32),
    Dense(1, activation='sigmoid')
])


model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])


model.fit(padded_sequences, labels, epochs=10)


loss, accuracy = model.evaluate(padded_sequences, labels)
print(f"Accuracy: {accuracy}")


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


ValueError: Unrecognized data type: x=[[ 1  3  4  5  0  0]
 [ 2  6  7  8  0  0]
 [ 9 10 11 12 13 14]
 [ 1  2 15  0  0  0]] (of type <class 'numpy.ndarray'>)